### ISSUE TITLE
table not existing: tx_cartevents_domain_model_category (new Extbase Persistence Configuration)

### ISSUE THREAD

**Issue by tastensolo** [extcode/cart_events#71]
While using category object you need following configuration for datamapping:

needed file: cart_events/Configuration/Extbase/Persistence/Classes.php 

```
<?php
declare(strict_types = 1);

return [
    \Extcode\CartEvents\Domain\Model\Category::class => [
        'recordType' => '\Extcode\CartEvents\Domain\Model\Category',
        'tableName' => 'sys_category',
    ]
];
```
otherwise the dataMapper searched for table tx_cartevents_domain_model_category, which does not exists.

Thanks for adjustment!

**Comment by extcode** [comment]
I added the configuration of the table (tableName), but did not set the recordType explicitly, because it should be possible that one can use all categories independently of this extension. I think explicitly restricting this can be set in own site package extension.
