### ISSUE TITLE
Error finding by category in eventRepository V5dev

### ISSUE THREAD

**Issue by slowhand11** [extcode/cart_events#90]
Change:
`        if (!empty($demand->getCategories())) {
            $categoryConstraints = [];
            foreach ($demand->getCategories() as $category) {
                $categoryConstraints[] = $query->contains('category', $category);
                $categoryConstraints[] = $query->contains('categories', $category);
            }
            $constraints = $query->logicalOr($categoryConstraints);
        }`
To:
`        if (!empty($demand->getCategories())) {
            $categoryConstraints = [];
            foreach ($demand->getCategories() as $category) {
                $categoryConstraints[] = $query->equals('category', $category);
                $categoryConstraints[] = $query->equals('categories', $category);
            }
            $constraints = $query->logicalOr(...array_values($categoryConstraints));
        }`

**Comment by extcode** [comment]
I've created a PR. But because you can assign several categories to `categories`, I left it at `$query->contains`. Can you please check whether the change solves the problem?

**Comment by slowhand11** [comment]
Hi, looks like ist working. Thanks for quick responese.
